### ISSUE TITLE
php7: symbol lookup error: /usr/local/php7/lib/php/extensions/debug-non-zts-20160303/phpng_xhprof.so: undefined symbol: get_tsc_from_u

### ISSUE THREAD

**Issue by toxmc** [Yaoguais/phpng-xhprof#10]
[root@server-124 diff]# php7 -v
PHP 7.1.1 (cli) (built: Jan 18 2017 19:26:04) ( NTS DEBUG )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies

[root@server-124 diff]# php7 --ri xhprof
xhprof
xhprof => 0.9.5
CPU num => 1

strace info

getcwd("/home/xmc/phpng-xhprof-master/diff", 4096) = 35
lstat("/home/xmc/phpng-xhprof-master/diff/sample.php", {st_mode=S_IFREG|0664, st_size=540, ...}) = 0
lstat("/home/xmc/phpng-xhprof-master/diff", {st_mode=S_IFDIR|0775, st_size=289, ...}) = 0
lstat("/home/xmc/phpng-xhprof-master", {st_mode=S_IFDIR|0775, st_size=4096, ...}) = 0
lstat("/home/xmc", {st_mode=S_IFDIR|0700, st_size=4096, ...}) = 0
lstat("/home", {st_mode=S_IFDIR|0755, st_size=28, ...}) = 0
rt_sigaction(SIGPROF, NULL, {SIG_DFL, [], 0}, 8) = 0
rt_sigaction(SIGPROF, {0xa74f74, ~[ILL TRAP ABRT BUS FPE KILL SEGV CONT STOP TSTP TTIN TTOU SYS RTMIN RT_1], SA_RESTORER|SA_SIGINFO, 0x7f75328b4b20}, NULL, 8) = 0
rt_sigaction(SIGHUP, NULL, {SIG_DFL, [], 0}, 8) = 0
rt_sigaction(SIGHUP, {0xa74f74, ~[ILL TRAP ABRT BUS FPE KILL SEGV CONT STOP TSTP TTIN TTOU SYS RTMIN RT_1], SA_RESTORER|SA_SIGINFO, 0x7f75328b4b20}, NULL, 8) = 0
rt_sigaction(SIGINT, NULL, {SIG_DFL, [], 0}, 8) = 0
rt_sigaction(SIGINT, {0xa74f74, ~[ILL TRAP ABRT BUS FPE KILL SEGV CONT STOP TSTP TTIN TTOU SYS RTMIN RT_1], SA_RESTORER|SA_SIGINFO, 0x7f75328b4b20}, NULL, 8) = 0
rt_sigaction(SIGQUIT, NULL, {SIG_DFL, [], 0}, 8) = 0
rt_sigaction(SIGQUIT, {0xa74f74, ~[ILL TRAP ABRT BUS FPE KILL SEGV CONT STOP TSTP TTIN TTOU SYS RTMIN RT_1], SA_RESTORER|SA_SIGINFO, 0x7f75328b4b20}, NULL, 8) = 0
rt_sigaction(SIGTERM, NULL, {SIG_DFL, [], 0}, 8) = 0
rt_sigaction(SIGTERM, {0xa74f74, ~[ILL TRAP ABRT BUS FPE KILL SEGV CONT STOP TSTP TTIN TTOU SYS RTMIN RT_1], SA_RESTORER|SA_SIGINFO, 0x7f75328b4b20}, NULL, 8) = 0
rt_sigaction(SIGUSR1, NULL, {SIG_DFL, [], 0}, 8) = 0
rt_sigaction(SIGUSR1, {0xa74f74, ~[ILL TRAP ABRT BUS FPE KILL SEGV CONT STOP TSTP TTIN TTOU SYS RTMIN RT_1], SA_RESTORER|SA_SIGINFO, 0x7f75328b4b20}, NULL, 8) = 0
rt_sigaction(SIGUSR2, NULL, {SIG_DFL, [], 0}, 8) = 0
rt_sigaction(SIGUSR2, {0xa74f74, ~[ILL TRAP ABRT BUS FPE KILL SEGV CONT STOP TSTP TTIN TTOU SYS RTMIN RT_1], SA_RESTORER|SA_SIGINFO, 0x7f75328b4b20}, NULL, 8) = 0
rt_sigaction(SIGPROF, {0xa74f74, ~[ILL TRAP ABRT BUS FPE KILL SEGV CONT STOP TSTP TTIN TTOU SYS RTMIN RT_1], SA_RESTORER|SA_SIGINFO, 0x7f75328b4b20}, NULL, 8) = 0
rt_sigprocmask(SIG_UNBLOCK, [PROF], NULL, 8) = 0
mmap(NULL, 65536, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f75352e5000
stat("", 0x7fffd5bafdc0)                = -1 ENOENT (No such file or directory)
fstat(0, {st_mode=S_IFCHR|0620, st_rdev=makedev(136, 1), ...}) = 0
fstat(0, {st_mode=S_IFCHR|0620, st_rdev=makedev(136, 1), ...}) = 0
lseek(0, 0, SEEK_CUR)                   = -1 ESPIPE (Illegal seek)
fstat(1, {st_mode=S_IFCHR|0620, st_rdev=makedev(136, 1), ...}) = 0
fstat(1, {st_mode=S_IFCHR|0620, st_rdev=makedev(136, 1), ...}) = 0
lseek(1, 0, SEEK_CUR)                   = -1 ESPIPE (Illegal seek)
fstat(2, {st_mode=S_IFCHR|0620, st_rdev=makedev(136, 1), ...}) = 0
fstat(2, {st_mode=S_IFCHR|0620, st_rdev=makedev(136, 1), ...}) = 0
lseek(2, 0, SEEK_CUR)                   = -1 ESPIPE (Illegal seek)
mmap(NULL, 151552, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f75352c0000
getcwd("/home/xmc/phpng-xhprof-master/diff", 4096) = 35
ioctl(3, TCGETS, 0x7fffd5bae8f0)        = -1 ENOTTY (Inappropriate ioctl for device)
fstat(3, {st_mode=S_IFREG|0664, st_size=540, ...}) = 0
mmap(NULL, 572, PROT_READ, MAP_PRIVATE, 3, 0) = 0x7f753540a000
munmap(0x7f753540a000, 572)             = 0
close(3)                                = 0
munmap(0x7f753540b000, 4096)            = 0
sched_getaffinity(6960, 128, [1, 0, 7f7527640a30, 7f7532888458, 0, 7fffd5baeb00, 433700, 7f7535202db0]) = 8
sched_setaffinity(0, 128, [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2cb, 0, 7fffd5baeb20, 7f7527643b53, 7f752ee58420, 27846368, 7fffd5baeb40, 7f7527642ac5, 0, 975e2021199a0, 7fffd5baeb70, 7f752764494d, 0, 975e2, 7fffd5baebb0, 100a93642, ...]) = 0
nanosleep({0, 0}, NULL)                 = 0
nanosleep({0, 5000000}, NULL)           = 0
sched_setaffinity(0, 128, [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...]) = 0
sched_setaffinity(0, 128, [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 7b, 0, 7fffd5baeb40, 7f7527642aec, 0, 975e2021199a0, 7fffd5baeb70, 7f752764494d, 0, 975e2, 7fffd5baebb0, 100a93642, 7fffd5baeba0, 7f7527642476, 7fffd5baebb0, 7f752ee13230, ...]) = 0
writev(2, [{"php7", 4}, {": ", 2}, {"symbol lookup error", 19}, {": ", 2}, {"/usr/local/php7/lib/php/extensio"..., 73}, {": ", 2}, {"undefined symbol: get_tsc_from_u"..., 33}, {"", 0}, {"", 0}, {"\n", 1}], 10php7: symbol lookup error: /usr/local/php7/lib/php/extensions/debug-non-zts-20160303/phpng_xhprof.so: undefined symbol: get_tsc_from_us
) = 136
exit_group(127)                         = ?
+++ exited with 127 +++

**Comment by yaoguais** [comment]
undefined symbol: get_tsc_from_us? make failed ?

```
phpng_xhprof.c:1142
/**
 * Convert microseconds to equivalent TSC counter ticks
 *
 * @param uint64 microseconds
 * @param double cpu_frequency, the CPU clock rate (MHz)
 * @return 64 bit unsigned integer
 *
 * @author veeve
 */
inline uint64 get_tsc_from_us(uint64 usecs, double cpu_frequency)
{
	return (uint64) (usecs * cpu_frequency);
}
```
