### ISSUE TITLE
phpng-xhprof run error after compiled

### ISSUE THREAD

**Issue by javacty** [Yaoguais/phpng-xhprof#2]
php version:
PHP 7.1.0-dev (cli) (built: Oct 22 2015 09:42:21) ( NTS )
Copyright (c) 1997-2015 The PHP Group
Zend Engine v3.0.0-dev, Copyright (c) 1998-2015 Zend Technologies

I had compiled xhprof.so, but when I test:
php -i | grep xhprof:
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/php7/lib/php/extensions/no-debug-non-zts-20151012/xhprof.so' - /usr/local/php7/lib/php/extensions/no-debug-non-zts-20151012/xhprof.so: cannot open shared object file: No such file or directory in Unknown on line 0
Warning: PHP Startup: Unable to load dynamic library '/usr/local/php7/lib/php/extensions/no-debug-non-zts-20151012/xhprof.so' - /usr/local/php7/lib/php/extensions/no-debug-non-zts-20151012/xhprof.so: cannot open shared object file: No such file or directory in Unknown on line 0

**Comment by yaoguais** [comment]
see readme,and try again.it is phpng_xhprof.so not xhprof.so.
[xhprof]
extension = phpng_xhprof.so
xhprof.output_dir = /tmp/xhprof

**Comment by javacty** [comment]
thanks very much !
 :P
