### ISSUE TITLE
执行错误

### ISSUE THREAD

**Issue by glowdan** [Yaoguais/phpng-xhprof#3]
能正确安装，但是会报错。

> PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/php/lib/php/extensions/no-debug-zts-20151012/phpng_xhprof.so' - /usr/local/php/lib/php/extensions/no-debug-zts-20151012/phpng_xhprof.so: undefined symbol: _tsrm_ls_cache in Unknown on line 0

**Comment by yaoguais** [comment]
好的，我检查下，PHP版本是多少呢?

**Comment by glowdan** [comment]
7.0.4

**Comment by yaoguais** [comment]
我这边是在debug模式编译后仍然会有memory leaks，但是没有出现Unable to load的情况，跑tests也是可以的，跑diff下面的脚本也正常执行。
我从官网下的源码包，编译参数: ./configure --prefix=/root/php7d --without-pear --enable-fpm --enable-debug
你能给一下你的编译参数吗？我这里没有重现这个错误.

**Comment by glowdan** [comment]
我没有使用其他参数。直接configure的。服务器是CentOS release 6.6。

**Comment by yaoguais** [comment]
我的centos6.5也是直接./configure(这个我也试过了的),也没有出现这个问题呢，这个提示是跟线程安全相关的。
我的PHP编译模式：NTS,debug，非线程安全的debug模式。你是不是线程安全了的？

```
[root@dev php-7.0.4]# /root/php7d/bin/php -i
phpinfo()
PHP Version => 7.0.4

System => Linux dev 2.6.32-431.el6.x86_64 #1 SMP Fri Nov 22 03:15:09 UTC 2013 x86_64
Build Date => Mar 28 2016 12:37:59
Configure Command =>  './configure'  '--prefix=/root/php7d' '--without-pear' '--enable-fpm' '--enable-debug'
Server API => Command Line Interface
Virtual Directory Support => disabled
Configuration File (php.ini) Path => /root/php7d/lib
Loaded Configuration File => /root/php7d/lib/php.ini
Scan this dir for additional .ini files => (none)
Additional .ini files parsed => (none)
PHP API => 20151012
PHP Extension => 20151012
Zend Extension => 320151012
Zend Extension Build => API320151012,NTS,debug
PHP Extension Build => API20151012,NTS,debug
Debug Build => yes
Thread Safety => disabled
Zend Signal Handling => disabled
Zend Memory Manager => enabled
Zend Multibyte Support => disabled
IPv6 Support => enabled
DTrace Support => disabled

```

**Comment by glowdan** [comment]
对的，我今天看了。是线程安全的了。准备换掉。谢谢啦。

**Comment by glowdan** [comment]
加下好友吧，大神。

**Comment by yaoguais** [comment]
不客气，这个扩展问题还不少，目前发现的大概有两个，memory leak跟call_user_function系列不兼容，还有待解决。

**Comment by Yaoguais** [comment]
不客气，这个扩展问题还不少，目前发现的大概有两个，memory leak跟call_user_function系列不兼容，还有待解决。
