### ISSUE TITLE
undefined symbol: _tsrm_ls_cache in Unknown on line 0

### ISSUE THREAD

**Issue by ghost** [Yaoguais/phpng-xhprof#4]
安装完成后提示：
`PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/php7/lib/php/extensions/no-debug-zts-20151012/phpng_xhprof.so' - /usr/local/php7/lib/php/extensions/no-debug-zts-20151012/phpng_xhprof.so: undefined symbol: _tsrm_ls_cache in Unknown on line 0`

**Comment by yaoguais** [comment]
问题的解决办法可以参考issue#3
