### ISSUE TITLE
execute_ex_replace函数最后为什么不再调用一下zend_execute_ex

### ISSUE THREAD

**Issue by imaben** [Yaoguais/phpng-xhprof#5]
现在加上你这个扩展之后，其它有重写zend_execute_ex的扩展的确不生效，为什么不在最后再调用一下呢？会有什么问题吗？

**Comment by yaoguais** [comment]
因为其他扩展大都是包裹zend_execute_ex，而execute_ex_replace是完全替换了这个函数，那么你在execute_ex_replace函数内部那个位置调用zend_execute_ex合适呢？目前我没有找到合适的位置。

**Comment by joostshao** [comment]
http://php.net/manual/en/migration55.internals.php
为什么zend_execute_ex这个可以在各自的ext里面被重写呢？ 

这里自己重新实现了一个execute_ex_replace有什么作用呢？
我看5版本里面也确实没有使用到，这个是不是有问题呢？

**Comment by yaoguais** [comment]
```
各自的扩展实现是包裹zend_execute_ex函数的，所以不能修改zend_execute_ex函数内部的代码。
重写的目的就是修改函数内部的代码。
另外一个这个扩展并不兼容php7以前的版本。
```
